### ISSUE TITLE
FP for NISSAN LEAF 2018 Instrument Cluster

### ISSUE THREAD

**Issue by tibora** [razem-io/openpilot#2]
Here is the result from UserAdmin:

    carFw = [
      ( ecu = engine,
        fwVersion = "5SH4A\003AB\a5SH4APSMT04\000\000\000\x80",
        address = 1943,
        subAddress = 0 ),
      ( ecu = eps,
        fwVersion = "5SH2A\x99A\005\002N123F\025\x81\000\000\000\000\000\000\000\x80",
        address = 1858,
        subAddress = 0 ),
      ( ecu = transmission,
        fwVersion = "5SA2B\004AB\a1\003\x80\022P\002\003D\000\002\006\000\000\000\x80",
        address = 1949,
        subAddress = 0 ) ],

And the one from the fw_versions.py:

Getting vin...
vin query retry (1) ...
vin query retry (2) ...
vin query retry (3) ...
vin query retry (4) ...
vin query retry (5) ...
vin query retry (6) ...
vin query retry (7) ...
vin query retry (8) ...
vin query retry (9) ...
vin query retry (10) ...
VIN: 00000000000000000
Getting VIN took 1.098 s

  0%|                                                     | 0/3 [00:00<?, ?it/s]FW query exception: Traceback (most recent call last):
  File "selfdrive/car/fw_versions.py", line 353, in get_fw_versions
    fw_versions.update(query.get_data(t))
  File "/data/pythonpath/selfdrive/car/isotp_parallel_query.py", line 107, in get_data
    dat: Optional[bytes] = msg.recv()
  File "/data/pythonpath/panda/python/uds.py", line 401, in recv
    self._isotp_rx_next(msg)
  File "/data/pythonpath/panda/python/uds.py", line 443, in _isotp_rx_next
    assert self.rx_idx & 0xF == rx_data[0] & 0xF, "isotp - rx: invalid consecutive frame index"
AssertionError: isotp - rx: invalid consecutive frame index

100%|█████████████████████████████████████████████| 3/3 [00:04<00:00,  1.36s/it]

Found FW versions
{
  (Ecu.engine, 0x797, None): [b'5SH4A\x03AB\x075SH4APSMT04\x00\x00\x00\x80']
  (Ecu.eps, 0x742, None): [b'5SH2A\x99A\x05\x02N123F\x15\x81\x00\x00\x00\x00\x00\x00\x00\x80']
  (Ecu.transmission, 0x79d, None): [b'5SA2B\x04AB\x071\x03\x80\x12P\x02\x03D\x00\x02\x06\x00\x00\x00\x80']
}

Possible matches: {'NISSAN LEAF 2018 Instrument Cluster'}
Getting fw took 4.116 s

**Comment by razem-io** [comment]
Thank you, for the fingerprint. It is already in `values.py`. You should be good to go :). Closing.
